In [3]:
import torch

In [13]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

c = torch.where(a == 3)[0]
print(c)
print(list(c.shape)[0])

tensor([], dtype=torch.int64)
0


In [1]:
import bitcoin

data = bitcoin.BitcoinOTC()

data.

c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


6005

In [10]:
a = torch.distributions.Bernoulli(logits=torch.tensor(-2.0))

b = a.sample()
b.type()

'torch.FloatTensor'

In [9]:
import bitcoin

data = bitcoin.BitcoinOTC()

c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
c:\users\andrew\anaconda3\envs\ppp\lib\site-packages\numpy\core\_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [25]:
a = torch.tensor([[10, 5, 8],[2, 1, 3]])
a.index_select(-1, torch.tensor([2, 1]))

tensor([[8, 5],
        [3, 1]])

In [6]:
b = torch.Tensor([[1,2],[3,4],[5,6]])
b.shape

torch.Size([3, 2])

In [8]:
import numpy as np

a = np.array([2,3,1,2,3])
a.tolist()

[2, 3, 1, 2, 3]

In [30]:
torch.as_tensor(np.arange(4)[np.random.binomial(1, 0.5, size=4) == 1], dtype=torch.long)

tensor([1, 3])

In [32]:
from torch_cluster import random_walk

row = torch.tensor([0, 1, 1, 1, 2, 2, 3, 3, 4, 4])
col = torch.tensor([1, 0, 2, 3, 1, 4, 1, 4, 2, 3])
start = torch.tensor([0, 1, 2, 3, 4])

walk = random_walk(row, col, start, walk_length=3)
print(walk)

tensor([[0, 1, 2, 4],
        [1, 2, 4, 3],
        [2, 4, 2, 4],
        [3, 1, 0, 1],
        [4, 3, 1, 0]])


In [44]:
b = torch.tensor([[1,2,3,3,3],[2,1,4,4,5]])


tensor([[1, 2, 3, 3, 3],
        [2, 1, 4, 4, 5]])
tensor([1, 2, 3, 3])
tensor([2, 3, 3, 3])


In [53]:
b = np.array([[1,2,3,4,5],[2,3,4,5,6]])
np.where((b[0, :] == 2) & (b[1, :] == 3))[0][0]

1

In [14]:
data = bitcoin.BitcoinOTC()

In [15]:
sample_str = 'random-walk'
sample_args = {'start_num': 5, 'walk_length': 50}
print(data.nodes_pos_degree_mask)
print(data.edges_pos_degree_mask)

tensor([   0,    1,    3,  ..., 5994, 5995, 5998])
tensor([    0,     1,     2,  ..., 35589, 35590, 35591])


In [4]:
len(data.pos_degree_mask)

4791

In [14]:
%load_ext autoreload
%autoreload 1
%aimport bitcoin

In [16]:
import torch
import numpy as np
from torch_cluster import random_walk

data = bitcoin.BitcoinOTC()

In [276]:
start_num = 5
walk_length = 60

start_loc = torch.as_tensor(
    np.random.choice(data.nodes_pos_degree_mask.numpy(), size=start_num, replace=False),
    dtype=torch.long
)
print(start_loc)

# Perform random walks; note that walks has shape
# [start_num, walk_length + 1]

row_new = data.edge_index[0, data.edges_pos_degree_mask]
col_new = data.edge_index[1, data.edges_pos_degree_mask]

_, perm = torch.sort(row_new*data.num_nodes + col_new)
row_new, col_new = row_new[perm], col_new[perm]

walks = random_walk(row=row_new,
                    col=col_new,
                    start=start_loc,
                    num_nodes=data.num_nodes,
                    walk_length=walk_length)

# Convert into edge list
edge_list = torch.zeros(size=(2, start_num*walk_length),
                        dtype=torch.long)

for i in range(start_num):
    ind = i*walk_length + np.arange(walk_length)
    ind = list(ind)
    edge_list[0, ind] = walks[i, :-1]
    edge_list[1, ind] = walks[i, 1:]
    
# Extract nodes and the indices of edge_list with respect to
# self.edge_index
node_ind = torch.unique(edge_list)

edge_ind = torch.zeros(size=[edge_list.shape[1]], dtype=torch.long)

for i in range(edge_list.shape[1]):
    b = (data.edge_index[0, :] == edge_list[0, i]) & (data.edge_index[1, :] == edge_list[1, i])
    a = torch.where(b)[0]
    edge_ind[i] = a[0]
    
print(edge_ind)

tensor([3206, 1049, 4300, 3665, 4748])


IndexError: index 0 is out of bounds for dimension 0 with size 0

In [94]:
subsample_dict = {'node_ind': node_ind, 'edge_ind': edge_ind,
                  'edge_list': edge_list}

print(subsample_dict)

{'node_ind': tensor([   6,   34,   40,   95,  149,  303,  435,  519,  734,  797,  831,  861,
         867,  934, 1033, 1160, 1216, 1347, 1395, 1457, 1554, 1561, 1621, 2062,
        2084, 2088, 2223, 2261, 2298, 2304, 2457, 2641, 2724, 2816, 3201, 3597,
        3652, 3653, 3736, 3804, 3874, 4087, 4196, 4314, 4458]), 'edge_ind': tensor([ 6508, 34397,  7241, 20290,  6086,  3659, 10310, 11728,  2043,  3610,
         3810,  3575,  4326,  3617,  3576,  7777, 32423,  5001,  6694,  7529,
        16576,  6682,  7334,  6695,  7569, 35363, 10738, 10278, 12065, 12046,
        12097, 22026, 11778, 11964, 12716, 17505, 16936, 15446, 16512, 16937,
        18310, 12715, 19962, 19449, 20510, 20294, 23033, 29604, 24448]), 'edge_list': tensor([[   6,   34,   34,   34,   40,  149,  303,  435,  519,  734,  797,  831,
          831,  861,  867,  934, 1033, 1160, 1216, 1216, 1216, 1347, 1395, 1457,
         1554, 2062, 2084, 2088, 2223, 2223, 2261, 2261, 2298, 2304, 2457, 2641,
         2641, 2724, 2816, 320

In [97]:
data = bitcoin.BitcoinOTC()

sample_str = 'random-walk'
sample_args = {'start_num': 5, 'walk_length': 50}

test = data.subsample(sample_str=sample_str, sample_args=sample_args)
print(test)

{'node_ind': tensor([   0,    3,    6,   16,   18,   34,   40,   55,   56,   59,  103,  134,
         140,  142,  143,  170,  180,  208,  213,  215,  226,  229,  246,  379,
         395,  400,  416,  461,  473,  492,  494,  521,  522,  534,  544,  545,
         575,  591,  629,  646,  651,  686,  708,  713,  728,  734,  756,  766,
         792,  793,  845,  855,  861,  881,  907,  921,  927,  985, 1008, 1012,
        1017, 1047, 1093, 1118, 1244, 1266, 1316, 1333, 1351, 1362, 1393, 1395,
        1411, 1501, 1554, 1561, 1564, 1565, 1574, 1582, 1583, 1584, 1618, 1636,
        1638, 1692, 1713, 1724, 1734, 1753, 1801, 1809, 1818, 1839, 1893, 1898,
        1899, 1952, 1976, 1977, 2016, 2018, 2027, 2044, 2066, 2134, 2158, 2279,
        2290, 2295, 2305, 2321, 2343, 2484, 2485, 2502, 2634, 2641, 2657, 2680,
        2709, 2724, 2726, 2727, 2777, 2847, 2857, 2859, 2867, 2873, 2908, 2909,
        2933, 2979, 3001, 3017, 3145, 3173, 3184, 3218, 3220, 3226, 3253, 3282,
        3365, 3403, 3464, 3

In [98]:
test = data.subsample(sample_str=sample_str, sample_args=sample_args)
print(test)

{'node_ind': tensor([   1,    5,    6,    9,   12,   20,   22,   27,   31,   34,   40,   59,
          60,   61,   63,   87,  103,  108,  109,  131,  140,  141,  142,  143,
         148,  158,  161,  162,  163,  197,  200,  205,  208,  228,  232,  256,
         265,  267,  272,  281,  295,  296,  299,  305,  324,  349,  409,  416,
         418,  442,  451,  455,  458,  483,  487,  498,  500,  522,  533,  534,
         557,  569,  570,  584,  591,  605,  617,  624,  646,  653,  686,  713,
         778,  779,  792,  804,  831,  881,  896,  922,  924,  952,  962,  966,
        1004, 1017, 1043, 1047, 1049, 1097, 1145, 1184, 1200, 1212, 1219, 1251,
        1314, 1316, 1365, 1395, 1399, 1486, 1519, 1554, 1555, 1564, 1565, 1584,
        1585, 1590, 1610, 1628, 1633, 1692, 1730, 1742, 1809, 1884, 1947, 1952,
        1966, 2016, 2027, 2033, 2044, 2066, 2069, 2070, 2071, 2075, 2084, 2103,
        2108, 2109, 2143, 2166, 2172, 2261, 2305, 2377, 2387, 2598, 2613, 2617,
        2683, 2715, 2754, 2

In [108]:
a = [0 for i in range(5)]
a[0] = np.array([2,3,5])
torch.distributions.Normal(torch.tensor(0), torch.tensor(2))

Normal(loc: 0, scale: 2)